### ISSUE TITLE
NullPointerException in fillLeft method

### ISSUE THREAD

**Issue by riggaroo** [jess-anders/two-way-gridview#28]
Hi, 
I have been receiving a few crashes from crashlytics recently in the TwoWayGridView, which I cannot seem to reproduce:
Stacktrace:

java.lang.NullPointerException
       at com.jess.ui.TwoWayGridView$HorizontalGridBuilder.fillLeft()
       at com.jess.ui.TwoWayGridView$HorizontalGridBuilder.makeAndAddView()
       at com.jess.ui.TwoWayGridView.lookForSelectablePosition()
       at com.jess.ui.TwoWayAbsListView$HorizontalTouchHandler.getFlingRunnable()
       at com.jess.ui.TwoWayAbsListView$HorizontalTouchHandler$HorizontalFlingRunnable.run()
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5306)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ShoaibKakal** [comment]
it occurs when a variable is accessed which is not pointing to any object and refers to nothing or null.
